#!/bin/sh

umask 0002 || exit 1

REPOS="$1"
TXN="$2"

# must use log messages you aloof little bitches
svnlook log -t "$TXN" "$REPOS" | grep "[a-zA-Z0-9]" || { echo "Empty logfiles are disallowed." >&2 ; exit 1 ; }
